import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children, indivi, team }) {
  return (
     <html>
+      <body className="w-screen h-screen flex">
      <div className="w-[25%] bg-amber-950">{children}</div>
      <div className="w-[50%] bg-amber-300" >{indivi}</div>
      <div className="w-[25%] bg-amber-950">{team}</div>
      </body>
    </html>
  );
}